### ISSUE TITLE
Confused about input files for Main Class

### ISSUE THREAD

**Issue by vietcuongk99** [Nakwendaa/phylogeny-neighbor-joining#1]
Can you explain about 3 input file for execute main function in PhylogenyNeighborJoining.class ? 
I understand BLOSUM62.txt that contain distance matrix, but what about these others input ? Can you give me more details about this ?
Thank you.

**Comment by Nakwendaa** [comment]
It's been quite a while since I did this assignment, so I don't remember everything. But I'll try to answer it as best as I can :)
Use Deepl if necessary to understand my comments in French.

For the file arbres.nw, it's just a way to represent a binary tree:
https://en.wikipedia.org/wiki/Newick_format

For the proteins.fa file, it simply corresponds to amino acid sequences.

So in the trees.nw file, OR2J3_Human has the amino acid sequence of the proteins.fa file:
--------------------------MNDDGKVNASSEGYFILVGF----SNWPHL---E
VVIFVVVLIFYLM--------------TLIGNLFIIILSYLDSHLHTPMYFFLSNLSFLD
LCYTTSSIPQLLVNLWGPEKTISYAGCMIQLYFVLALGTTECVLLVVMSYDRYAAVCRPL
HYTVLMHPR-----FCHLLAVASWVSGFTNSALHSSFTFWVPLCGH----RQVDHFFCEV
PALLRL------------------------------SCVDTHVNELTLMITSSIFVLIPL
ILILTSYGAIVRAVLRMQ-STTGLQKVFGTCGAHLMAVSLFFIPAMCIYLQPPSGNSQDQ
GKFIALFYTVVTPSLNPLIYTLRNKVV

The aim of the assignment was to construct an NJ tree corresponding to the alignment of protein sequences (proteins.fa) using the **mutation weight matrix** of the blosum62 file. The cell in row r and column c gives the weight of a mutation from amino acid r to amino acid c. The distance between two amino acid sequences Ai and Aj can be determined according to the following equation:

![image](https://user-images.githubusercontent.com/17987549/99829738-a910bf80-2b2a-11eb-85a3-aa8adac05f06.png)

M denotes the weight matrix and ck each column of the alignment. In my code, I do this step using the amino acid sequences (proteins.fa) and the weight matrix of the blosum62 mutations into a distance matrix.

If you are only interested in the neighbor-joining algorithm, you should find the implementation in: public static BinTree neighborJoining(double[][] matriceDistance, HashMap<Integer, Node> tableNoeud)

**Comment by vietcuongk99** [comment]
> It's been quite a while since I did this assignment, so I don't remember everything. But I'll try to answer it as best as I can :)
> Use Deepl if necessary to understand my comments in French.
> 
> For the file arbres.nw, it's just a way to represent a binary tree:
> https://en.wikipedia.org/wiki/Newick_format
> 
> For the proteins.fa file, it simply corresponds to amino acid sequences.
> 
> So in the trees.nw file, OR2J3_Human has the amino acid sequence of the proteins.fa file:
> --------------------------MNDDGKVNASSEGYFILVGF----SNWPHL---E
> VVIFVVVLIFYLM--------------TLIGNLFIIILSYLDSHLHTPMYFFLSNLSFLD
> LCYTTSSIPQLLVNLWGPEKTISYAGCMIQLYFVLALGTTECVLLVVMSYDRYAAVCRPL
> HYTVLMHPR-----FCHLLAVASWVSGFTNSALHSSFTFWVPLCGH----RQVDHFFCEV
> PALLRL------------------------------SCVDTHVNELTLMITSSIFVLIPL
> ILILTSYGAIVRAVLRMQ-STTGLQKVFGTCGAHLMAVSLFFIPAMCIYLQPPSGNSQDQ
> GKFIALFYTVVTPSLNPLIYTLRNKVV
> 
> The aim of the assignment was to construct an NJ tree corresponding to the alignment of protein sequences (proteins.fa) using the **mutation weight matrix** of the blosum62 file. The cell in row r and column c gives the weight of a mutation from amino acid r to amino acid c. The distance between two amino acid sequences Ai and Aj can be determined according to the following equation:
> 
> ![image](https://user-images.githubusercontent.com/17987549/99829738-a910bf80-2b2a-11eb-85a3-aa8adac05f06.png)
> 
> M denotes the weight matrix and ck each column of the alignment. In my code, I do this step using the amino acid sequences (proteins.fa) and the weight matrix of the blosum62 mutations into a distance matrix.
> 
> If you are only interested in the neighbor-joining algorithm, you should find the implementation in: public static BinTree neighborJoining(double[][] matriceDistance, HashMap<Integer, Node> tableNoeud

**Comment by vietcuongk99** [comment]
Very detailed answer. I understand now. I just have homework about compare UPGMA and Neighbor-Joining when implement in coding. Your assignment really help me solve this. Thank you.
